import React, { useState } from 'react';
import { Search, ChevronDown, ChevronUp, HelpCircle, IndianRupee, BarChart2, Zap } from 'lucide-react';

const UserGuidePage: React.FC = () => {
  const [searchQuery, setSearchQuery] = useState<string>('');
  const [openSections, setOpenSections] = useState<Record<string, boolean>>({
    'getting-started': true,
    'estimation': false,
    'comparison': false,
    'recommendations': false,
    'faq': false,
  });

  const toggleSection = (sectionId: string) => {
    setOpenSections({
      ...openSections,
      [sectionId]: !openSections[sectionId],
    });
  };

  const faqs = [
    {
      question: "How accurate are the price estimates?",
      answer: "Our price estimates are based on comprehensive market data, recent sales, and regional factors. While we strive for accuracy, prices can vary based on retailer promotions, availability, and market fluctuations. We typically achieve 90-95% accuracy for current-generation devices and 85-90% for older models."
    },
    {
      question: "Why do prices differ between locations?",
      answer: "Prices vary between locations due to several factors including local taxes, import duties, regional distribution costs, market competition, and purchasing power. Our system accounts for these regional differences to provide location-specific estimates."
    },
    {
      question: "How often is the pricing data updated?",
      answer: "Our pricing database is updated daily for popular devices and weekly for less common models. This ensures our estimates reflect current market conditions and price trends."
    },
    {
      question: "Can I trust the reasonability verdict?",
      answer: "Our reasonability verdicts are generated by analyzing the estimated fair market value against the actual price, considering factors like device age, specifications, condition, and market trends. While these verdicts provide helpful guidance, we recommend using them as one factor in your purchasing decisions."
    },
    {
      question: "How do you determine similar devices for comparison?",
      answer: "Similar devices are selected based on multiple factors including price range (±20%), key specifications, release timeframe, target market segment, and user case. Our algorithm prioritizes devices with the most relevant feature sets to ensure meaningful comparisons."
    }
  ];

  return (
    <div className="py-8 px-4 sm:px-6 lg:px-8">
      <div className="max-w-5xl mx-auto">
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-slate-800 mb-2">User Guide</h1>
          <p className="text-slate-600">
            Learn how to use Esti-Check's tools to get accurate price estimates and make informed purchasing decisions.
          </p>
        </div>

        {/* Search */}
        <div className="mb-8">
          <div className="relative">
            <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
              <Search className="h-5 w-5 text-slate-400" />
            </div>
            <input
              type="text"
              placeholder="Search the guide..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="block w-full pl-10 pr-3 py-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-teal-500 focus:border-transparent bg-white"
            />
          </div>
        </div>

        {/* Table of Contents */}
        <div className="bg-slate-50 rounded-xl p-6 mb-8 border border-slate-200">
          <h2 className="text-xl font-semibold text-slate-800 mb-4">Table of Contents</h2>
          <ul className="space-y-2">
            <li>
              <a href="#getting-started" className="text-teal-600 hover:text-teal-800 font-medium transition-colors">
                Getting Started
              </a>
            </li>
            <li>
              <a href="#estimation" className="text-teal-600 hover:text-teal-800 font-medium transition-colors">
                Using the Price Estimation Tool
              </a>
            </li>
            <li>
              <a href="#comparison" className="text-teal-600 hover:text-teal-800 font-medium transition-colors">
                Device Comparison
              </a>
            </li>
            <li>
              <a href="#recommendations" className="text-teal-600 hover:text-teal-800 font-medium transition-colors">
                Understanding Recommendations
              </a>
            </li>
            <li>
              <a href="#faq" className="text-teal-600 hover:text-teal-800 font-medium transition-colors">
                Frequently Asked Questions
              </a>
            </li>
          </ul>
        </div>

        {/* Guide Sections */}
        <div className="space-y-6">
          {/* Getting Started */}
          <section id="getting-started" className="bg-white rounded-xl shadow-md border border-slate-100 overflow-hidden">
            <button
              onClick={() => toggleSection('getting-started')}
              className="w-full flex justify-between items-center p-6 text-left focus:outline-none"
            >
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-full bg-teal-100 flex items-center justify-center text-teal-600">
                  <Zap className="w-5 h-5" />
                </div>
                <h2 className="text-xl font-semibold text-slate-800">Getting Started</h2>
              </div>
              {openSections['getting-started'] ? (
                <ChevronUp className="w-5 h-5 text-slate-500" />
              ) : (
                <ChevronDown className="w-5 h-5 text-slate-500" />
              )}
            </button>
            
            {openSections['getting-started'] && (
              <div className="px-6 pb-6">
                <div className="prose max-w-none text-slate-700">
                  <p>
                    Welcome to Esti-Check! This guide will help you navigate our platform and get the most out of our tools.
                    Esti-Check provides accurate price estimates and reasonability analysis for electronic devices to help you
                    make informed purchasing decisions.
                  </p>
                  
                  <h3 className="text-lg font-medium text-slate-800 mt-4 mb-2">Key Features</h3>
                  <ul className="space-y-2">
                    <li className="flex items-start gap-2">
                      <IndianRupee className="w-5 h-5 text-teal-600 flex-shrink-0 mt-0.5" />
                      <span>
                        <strong>Price Estimation Tool:</strong> Get accurate price estimates based on device specifications,
                        condition, brand, and your location.
                      </span>
                    </li>
                    <li className="flex items-start gap-2">
                      <BarChart2 className="w-5 h-5 text-teal-600 flex-shrink-0 mt-0.5" />
                      <span>
                        <strong>Reasonability Analysis:</strong> Understand if a price is fair with our detailed reasonability
                        verdict and supporting factors.
                      </span>
                    </li>
                    <li className="flex items-start gap-2">
                      <HelpCircle className="w-5 h-5 text-teal-600 flex-shrink-0 mt-0.5" />
                      <span>
                        <strong>Device Comparison:</strong> Compare multiple devices side-by-side to find the best option
                        for your needs and budget.
                      </span>
                    </li>
                  </ul>
                  
                  <h3 className="text-lg font-medium text-slate-800 mt-4 mb-2">Navigation</h3>
                  <p>
                    Use the navigation menu at the top of the page to access different tools:
                  </p>
                  <ul>
                    <li><strong>Home:</strong> Overview of Esti-Check's features</li>
                    <li><strong>Estimate:</strong> Access the price estimation tool</li>
                    <li><strong>Compare:</strong> Compare multiple devices</li>
                    <li><strong>Guide:</strong> Access this user guide</li>
                  </ul>
                </div>
              </div>
            )}
          </section>

          {/* Price Estimation Tool */}
          <section id="estimation" className="bg-white rounded-xl shadow-md border border-slate-100 overflow-hidden">
            <button
              onClick={() => toggleSection('estimation')}
              className="w-full flex justify-between items-center p-6 text-left focus:outline-none"
            >
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-full bg-teal-100 flex items-center justify-center text-teal-600">
                  <IndianRupee className="w-5 h-5" />
                </div>
                <h2 className="text-xl font-semibold text-slate-800">Using the Price Estimation Tool</h2>
              </div>
              {openSections['estimation'] ? (
                <ChevronUp className="w-5 h-5 text-slate-500" />
              ) : (
                <ChevronDown className="w-5 h-5 text-slate-500" />
              )}
            </button>
            
            {openSections['estimation'] && (
              <div className="px-6 pb-6">
                <div className="prose max-w-none text-slate-700">
                  <p>
                    The Price Estimation Tool provides accurate estimates based on device specifications, condition, 
                    brand, and location. Follow these steps to get an estimate:
                  </p>
                  
                  <h3 className="text-lg font-medium text-slate-800 mt-4 mb-2">Step 1: Select Device Type</h3>
                  <p>
                    Choose the type of device you want to estimate (smartphone, laptop, tablet, etc.). 
                    Each device type has specific specification fields relevant to that category.
                  </p>
                  
                  <h3 className="text-lg font-medium text-slate-800 mt-4 mb-2">Step 2: Enter Device Specifications</h3>
                  <p>
                    Fill in the device specifications form with as much detail as possible. Required fields include:
                  </p>
                  <ul>
                    <li><strong>Brand:</strong> The manufacturer of the device</li>
                    <li><strong>Model:</strong> The specific model name/number</li>
                    <li><strong>Release Year:</strong> When the device was first released</li>
                    <li><strong>Condition:</strong> The physical condition of the device</li>
                  </ul>
                  <p>
                    Additional specifications vary by device type but may include processor, RAM, storage,
                    screen size, camera details, etc. The more information you provide, the more accurate
                    your estimate will be.
                  </p>
                  
                  <h3 className="text-lg font-medium text-slate-800 mt-4 mb-2">Step 3: Review Results</h3>
                  <p>
                    After submitting the form, you'll receive:
                  </p>
                  <ul>
                    <li><strong>Estimated Price:</strong> The fair market value for your device</li>
                    <li><strong>Price Range:</strong> Minimum and maximum expected prices</li>
                    <li><strong>Reasonability Verdict:</strong> Assessment of whether the price is fair</li>
                    <li><strong>Platform Prices:</strong> Where to find the best deals</li>
                    <li><strong>Price Trends:</strong> How the price is expected to change</li>
                    <li><strong>Similar Devices:</strong> Comparison with alternatives</li>
                  </ul>
                  
                  <div className="bg-teal-50 p-4 rounded-lg mt-4">
                    <h4 className="font-medium text-teal-700 mb-2">Pro Tip</h4>
                    <p className="text-teal-700 text-sm">
                      For the most accurate estimate, always include the exact model name and number, 
                      and be honest about the device's condition. This ensures our algorithms can 
                      provide the most precise valuation possible.
                    </p>
                  </div>
                </div>
              </div>
            )}
          </section>

          {/* Device Comparison */}
          <section id="comparison" className="bg-white rounded-xl shadow-md border border-slate-100 overflow-hidden">
            <button
              onClick={() => toggleSection('comparison')}
              className="w-full flex justify-between items-center p-6 text-left focus:outline-none"
            >
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-full bg-teal-100 flex items-center justify-center text-teal-600">
                  <BarChart2 className="w-5 h-5" />
                </div>
                <h2 className="text-xl font-semibold text-slate-800">Device Comparison</h2>
              </div>
              {openSections['comparison'] ? (
                <ChevronUp className="w-5 h-5 text-slate-500" />
              ) : (
                <ChevronDown className="w-5 h-5 text-slate-500" />
              )}
            </button>
            
            {openSections['comparison'] && (
              <div className="px-6 pb-6">
                <div className="prose max-w-none text-slate-700">
                  <p>
                    The Device Comparison Tool allows you to compare multiple devices side-by-side
                    to make an informed decision. Here's how to use it:
                  </p>
                  
                  <h3 className="text-lg font-medium text-slate-800 mt-4 mb-2">Adding Devices to Compare</h3>
                  <ol>
                    <li>Click on "Add Device" to start adding devices to your comparison list</li>
                    <li>Select the device type from the dropdown menu</li>
                    <li>Enter the specifications for the device</li>
                    <li>Click "Add to Comparison" to add the device to your list</li>
                    <li>Repeat for each device you want to compare (minimum 2 devices)</li>
                  </ol>
                  
                  <h3 className="text-lg font-medium text-slate-800 mt-4 mb-2">Comparison Results</h3>
                  <p>
                    The comparison results include:
                  </p>
                  <ul>
                    <li><strong>Side-by-Side Specs:</strong> Direct comparison of all specifications</li>
                    <li><strong>Price Comparison:</strong> Value for money analysis</li>
                    <li><strong>Pros & Cons:</strong> Key advantages and disadvantages of each device</li>
                    <li><strong>Recommendation Score:</strong> Overall rating based on specs and price</li>
                    <li><strong>Best Choice For:</strong> Scenarios where each device excels</li>
                  </ul>
                  
                  <div className="bg-slate-100 p-4 rounded-lg mt-4">
                    <h4 className="font-medium text-slate-800 mb-2">Note</h4>
                    <p className="text-slate-700 text-sm">
                      For the most meaningful comparisons, compare devices within the same category
                      and with similar price points. While you can compare different types of devices,
                      the results may be less relevant.
                    </p>
                  </div>
                </div>
              </div>
            )}
          </section>

          {/* Understanding Recommendations */}
          <section id="recommendations" className="bg-white rounded-xl shadow-md border border-slate-100 overflow-hidden">
            <button
              onClick={() => toggleSection('recommendations')}
              className="w-full flex justify-between items-center p-6 text-left focus:outline-none"
            >
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-full bg-teal-100 flex items-center justify-center text-teal-600">
                  <HelpCircle className="w-5 h-5" />
                </div>
                <h2 className="text-xl font-semibold text-slate-800">Understanding Recommendations</h2>
              </div>
              {openSections['recommendations'] ? (
                <ChevronUp className="w-5 h-5 text-slate-500" />
              ) : (
                <ChevronDown className="w-5 h-5 text-slate-500" />
              )}
            </button>
            
            {openSections['recommendations'] && (
              <div className="px-6 pb-6">
                <div className="prose max-w-none text-slate-700">
                  <p>
                    Esti-Check provides various recommendations to help you make informed decisions.
                    Here's how to interpret them:
                  </p>
                  
                  <h3 className="text-lg font-medium text-slate-800 mt-4 mb-2">Reasonability Verdict</h3>
                  <p>
                    Our reasonability verdict indicates whether a price is fair based on the device's
                    specifications, condition, and current market value:
                  </p>
                  <ul>
                    <li><strong>Excellent Deal:</strong> Price is significantly below market value (15%+ below)</li>
                    <li><strong>Good Deal:</strong> Price is somewhat below market value (5-15% below)</li>
                    <li><strong>Fair Deal:</strong> Price aligns with market value (±5%)</li>
                    <li><strong>Poor Deal:</strong> Price is somewhat above market value (5-15% above)</li>
                    <li><strong>Overpriced:</strong> Price is significantly above market value (15%+ above)</li>
                  </ul>
                  
                  <h3 className="text-lg font-medium text-slate-800 mt-4 mb-2">Reasonability Factors</h3>
                  <p>
                    These factors explain why a price is considered reasonable or unreasonable:
                  </p>
                  <ul>
                    <li><strong>Market Trends:</strong> How current supply and demand affect pricing</li>
                    <li><strong>Regional Factors:</strong> Location-specific considerations</li>
                    <li><strong>Device Age:</strong> Impact of release date on value</li>
                    <li><strong>Condition:</strong> How the physical state affects pricing</li>
                    <li><strong>Special Features:</strong> Premium features that may increase value</li>
                  </ul>
                  
                  <h3 className="text-lg font-medium text-slate-800 mt-4 mb-2">Price Predictions</h3>
                  <p>
                    Our price predictions show how a device's value is expected to change over time:
                  </p>
                  <ul>
                    <li><strong>Stable:</strong> Price expected to remain consistent</li>
                    <li><strong>Declining:</strong> Price expected to decrease (common for tech)</li>
                    <li><strong>Increasing:</strong> Price expected to increase (rare, but possible for limited editions)</li>
                  </ul>
                  <p>
                    These predictions can help you decide whether to buy now or wait for a better price.
                  </p>
                  
                  <div className="bg-teal-50 p-4 rounded-lg mt-4">
                    <h4 className="font-medium text-teal-700 mb-2">Pro Tip</h4>
                    <p className="text-teal-700 text-sm">
                      Always consider both the reasonability verdict and price predictions together.
                      A "Fair Deal" on a device with rapidly declining value might not be as good as
                      it seems, while a "Poor Deal" on a device with stable or increasing value might
                      be worth considering.
                    </p>
                  </div>
                </div>
              </div>
            )}
          </section>

          {/* FAQ */}
          <section id="faq" className="bg-white rounded-xl shadow-md border border-slate-100 overflow-hidden">
            <button
              onClick={() => toggleSection('faq')}
              className="w-full flex justify-between items-center p-6 text-left focus:outline-none"
            >
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-full bg-teal-100 flex items-center justify-center text-teal-600">
                  <HelpCircle className="w-5 h-5" />
                </div>
                <h2 className="text-xl font-semibold text-slate-800">Frequently Asked Questions</h2>
              </div>
              {openSections['faq'] ? (
                <ChevronUp className="w-5 h-5 text-slate-500" />
              ) : (
                <ChevronDown className="w-5 h-5 text-slate-500" />
              )}
            </button>
            
            {openSections['faq'] && (
              <div className="px-6 pb-6">
                <div className="space-y-4">
                  {faqs.map((faq, index) => (
                    <div key={index} className="border-b border-slate-100 pb-4 last:border-b-0 last:pb-0">
                      <h3 className="text-lg font-medium text-slate-800 mb-2">{faq.question}</h3>
                      <p className="text-slate-700">{faq.answer}</p>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </section>
        </div>
      </div>
    </div>
  );
};

export default UserGuidePage;